### ISSUE TITLE
Day/week report(s) for Realtime users

### ISSUE THREAD

**Issue by Sipke82** [keallu/CSL-WatchIt#2]
Especially for Real Time users, the actual game stats are now a bit unsatisfying. 

> Perhaps its a good idea to be able to show some kind of "day-report"or even "week report" as a pop-up. This popup could then show all kinds of stats, like how many people used PT, the amount of tourists which entered the city, did that amusement park really make a profit over the whole day?
Perhaps it could even include some graph's?
Well we could brainstorm about the full contents of such reports but first we should know if it's even possible?

From:
https://github.com/dymanoid/RealTime/issues/164

Please let me know what you think. Thanks

**Comment by keallu** [comment]
Sorry for this very late reply. I absolutely think it is possible but my time are limited at the moment.

**Comment by keallu** [comment]
I've added this to my list of potential add-ons.
