### ISSUE TITLE
Request: Logging of stats

### ISSUE THREAD

**Issue by patrickkelso** [keallu/CSL-WatchIt#5]
I'm not a developer so feel free to tell me this won't work. I got the idea from a OpenTTD fork that did something similar and this mod looks like it's 95% of the way to what I want. 
https://github.com/grand-central-garbage/openttd-prometheus

I'd love it if these stats could be streamed to a CSV file (one line per interval with the city name and all the stats).

I'd then hoover up the stats with Telegraf send them off to Influx DB and make beautiful Grafana dashboards to display on my other screens while playing.

**Comment by keallu** [comment]
I think that would be a separate mod to stream different kind of stats to a CSV file that could be used further Telegraf and so on. Could you provide some more details about which specific information you would like to find in the CSV file? If you can make a kind of specification I might look into making such a mod.
